# Generated by Django 4.2.3 on 2024-01-18 18:08

from django.db import migrations, models
import django.db.models.deletion
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[news.validators.validate_title_words],
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="img/"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.user",
                    ),
                ),
                ("category", models.ManyToManyField(to="news.category")),
            ],
        ),
    ]
