# Generated by Django 4.2.3 on 2024-01-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_rename_category_news_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(),
        ),
    ]
